name: CI

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: oke-py/npm-audit-action@v1.4.0
        with:
          audit_level: critical
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: HUSKY_SKIP_INSTALL=1 npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        uses: paambaati/codeclimate-action@v2.5.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: "npm run test:coverage"
