name: Deploy to development

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install local dependencies
        run: HUSKY_SKIP_INSTALL=1 npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build
